server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/ledger_settlement
spring.datasource.username=postgres
spring.datasource.password=5566238
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none

ledger.fee-rate=0.031

spring.threads.virtual.enabled=true